### ISSUE TITLE
Active Directory integration when PHP is hosted on IIS

### ISSUE THREAD

**Issue by AlexRozen** [matomo-org/plugin-LoginLdap#114]
_SERVER["REMOTE_USER"] variable on the IIS hosted installation contains string like "DOMAINNAME\USER" instead of "USER@DOMAIN.NAME", so i had to fix one string in the file LoginLdap\Auth\WebServerAuth.php

was:

``` php
                $this->login = preg_replace('/@.*/', '', $webServerAuthUser);
```

new variant (sorry, I'm nubie, it's not optimal code):

``` php
        $this->login = preg_replace('/@.*/', '', preg_replace('/.*\\\\/', '', $webServerAuthUser));
```

**Comment by Phalynx** [comment]
I can confirm this workaround works with PHP 5.6 on IIS 7.5 on Windows Server 2008 R2 Standard Edition Service Pack 1

**Comment by mattab** [comment]
Hi @diosmosis could you review this change and apply to the plugin if looks good to you?
