### ISSUE TITLE
Could not bind as LDAP admin

### ISSUE THREAD

**Issue by ChristianLuxem** [matomo-org/plugin-LoginLdap#171]
Hi,
we have the following problem with the LoginLDAP plugin:
Matomo-Version: 3.5.0
 Logs:

[piwik.log](https://github.com/matomo-org/plugin-LoginLdap/files/2000257/piwik.log)

We tested the same credentials with the "test.php" and the output was "Query count: 1". 
LDAPSearch on linux is also working as expected.

Is there a bug in the version or is our configuration wrong?
Thanks,

**Comment by ChristianLuxem** [comment]
@mattab ,
i saw that you have some experience with this kind of issues, can you take a look into it?

**Comment by mattab** [comment]
@ChristianLuxem We can only help you and troubleshoot this issue, as part of our on-premises support subscription: https://matomo.org/support/

**Comment by brunowego** [comment]
@ChristianLuxem one question, your user have only read access right?

**Comment by mattab** [comment]
## Suggestions on fixing this issue

*  try prefixing the LDAP url by `ldaps://` and try again?
* Check the given admin credentials in Matomo's backend 
* also check the Ldap Searchfilter is correct eg. `(objectClass=person)`
* [check for LDAP connection issue.](https://github.com/matomo-org/plugin-LoginLdap/wiki/Troubleshooting#checking-for-an-ldap-server-configuration-issue) by issuing an `ldapsearch` command with the credentials you have configured with your ldap server.
