### ISSUE TITLE
After updating to piwik 3.8.0 Ldap stops working

### ISSUE THREAD

**Issue by tmcmm** [matomo-org/plugin-LoginLdap#176]
I've updated the Matomo version to the latest 3.8.0 but after the update it started to output the error:
**'Error: Wrong Username and password combination.?**
I have done some troubleshoot in order to check the connectivity and I'm having no luck.
from this command output it seems that the connectivity is OK:
**console loginldap:synchronize-users --login=<user> -vvv**

DEBUG [2019-01-23 11:26:44] 41820  UserSynchronizer::makeConfigured(): LDAP access synchronization not enabled.
DEBUG [2019-01-23 11:26:44] 41820  UserSynchronizer::makeConfigured: configuring with defaultSitesWithViewAccess = 
Synchronizing '<user>'...  DEBUG [2019-01-23 11:26:44] 41820  Model\LdapUsers: start getUser() with [array]
DEBUG [2019-01-23 11:26:44] 41820  Calling ldap_connect('<server_ip>', 389)
DEBUG [2019-01-23 11:26:44] 41820  ldap_connect result is [resource]
DEBUG [2019-01-23 11:26:44] 41820  anonymous ldap_bind call finished; connection ok
INFO [2019-01-23 11:26:44] 41820  LdapUsers::makeLdapClient: Using LDAP server 192.168.137.140:389
(..)
DEBUG [2019-01-23 11:26:44] 41820  ldap_bind result is '1'

from piwik.log:
INFO LoginLdap[2019-01-23 11:37:15 UTC] [da04d] LdapUsers::makeLdapClient: Using LDAP server <server_ip>:389
and no error..

**Comment by tpimpao** [comment]
Same problem here, ldap login is not working in 3.8.0 Version.

**Comment by BertrandGouny** [comment]
Same here, user API seems to ask a password : 
`
DEBUG LoginLdap[2019-01-23 16:17:19 UTC] [21092] UserSynchronizer::synchronizeLdapUser: synchronizing user [ piwik login = xxxx, ldap login = xxxx ]
DEBUG LoginLdap[2019-01-23 16:17:19 UTC] [21092] /var/www/matomo/plugins/UsersManager/API.php(901): Please enter your password to confirm this change.
DEBUG LoginLdap[2019-01-23 16:17:19 UTC] [21092] #0 /var/www/matomo/plugins/LoginLdap/LdapInterop/UserSynchronizer.php(141): Piwik\Plugins\UsersManager\API->updateUser('xxxx', 'xxxx...', 'xxxx...', 'xxxx xxxx', true)
DEBUG LoginLdap[2019-01-23 16:17:19 UTC] [21092] #1 /var/www/matomo/core/Access.php(628): Piwik\Plugins\LoginLdap\LdapInterop\UserSynchronizer->Piwik\Plugins\LoginLdap\LdapInterop\{closure}()
`

**Comment by tpimpao** [comment]
Exactly, same trace here, "Please enter your password to confirm this change" with no error on debug trace.

**Comment by BertrandGouny** [comment]
Thanks @tsteur, i manually updated to v4.0.6 and it fixed my problem. Just had to take care to clear all php cache.

**Comment by tsteur** [comment]
@tpimpao if you have the same trace as @BertrandGouny , then it looks like the plugin isn't updated to the latest version. You may need to manually download the plugin or make sure your PHP caches are all cleared.

**Comment by tpimpao** [comment]
Nice do hear that @BertrandGouny I miss clear de php cache. Testing right away.

**Comment by tsteur** [comment]
@BertrandGouny  thanks for letting us know that worked. I double checked and it should really fix the issue.
