### ISSUE TITLE
LDAP search for entries failed. (Unexpected Error, ldap_search returned null)

### ISSUE THREAD

**Issue by jota2016** [matomo-org/plugin-LoginLdap#178]
Hi all,

I am experiencing issues with the LoginLdap plugin (v4.0.6) and Matomo (v3.8.1).

An ldap search works fine with:

```
ldapsearch -H ldap://192.168.10.10 -b "dc=mydomain,dc=com" -D "CN=admin001,OU=Service Users,OU=Admin,DC=mydomain,DC=com" -W -z 3
```

This is the plugin configuration:

```
[LoginLdap]
servers[] = "ldap1.mydomain.com"
use_ldap_for_authentication = 1
enable_synchronize_access_from_ldap = 1
new_user_default_sites_view_access = ""
user_email_suffix = ""
required_member_of = ""
required_member_of_field = "memberOf"
ldap_user_filter = "objectClass=*"
ldap_user_id_field = "SamAccountName"
ldap_last_name_field = "sn"
ldap_first_name_field = "givenName"
ldap_alias_field = "cn"
ldap_mail_field = "mail"
ldap_password_field = "userPassword"
ldap_view_access_field = "view"
ldap_admin_access_field = "admin"
ldap_superuser_access_field = "superuser"
use_webserver_auth = 0
user_access_attribute_server_specification_delimiter = ";"
user_access_attribute_server_separator = ":"
instance_name = ""
ldap_network_timeout = "15"

[LoginLdap_ldap1]
hostname = "ldap1.mydomain.com"
port = 389
base_dn = "dc=mydomain,dc=com"
admin_user = "CN=admin001,OU=Service Users,OU=Admin,DC=mydomain,DC=com"
admin_pass = "xxxxxxxx"
```

But when try to connect to sync a user, it gives me an error:

```
./console loginldap:synchronize-users --login=admin001@mydomain.com -vvv
INFO [2019-03-08 11:36:36] 7891  UserAttributesParser::makeConfigured: Configured with no instance name so matching by URL, but server/site IDs separator set to special ':' character. This character may show up in URLs in LDAP, which will cause problems. We recommend you use a character not often found in URLs, such as '|'.
DEBUG [2019-03-08 11:36:36] 7891  UserSynchronizer::makeConfigured(): Using UserAccessMapper when synchronizing users.
DEBUG [2019-03-08 11:36:36] 7891  UserSynchronizer::makeConfigured: configuring with defaultSitesWithViewAccess = 
Synchronizing 'admin001@mydomain.com'...  DEBUG [2019-03-08 11:36:36] 7891  Model\LdapUsers: start getUser() with [array]
DEBUG [2019-03-08 11:36:36] 7891  Calling ldap_connect('192.168.10.10', 389)
DEBUG [2019-03-08 11:36:36] 7891  ldap_connect result is [resource]
DEBUG [2019-03-08 11:36:36] 7891  anonymous ldap_bind call finished; connection ok
INFO [2019-03-08 11:36:36] 7891  LdapUsers::makeLdapClient: Using LDAP server 192.168.10.10:389
DEBUG [2019-03-08 11:36:36] 7891  Calling ldap_bind([resource], 'CN=admin001,OU=Service Users,OU=Admin,DC=mydomain,DC=com', <password[length=10]>)
DEBUG [2019-03-08 11:36:36] 7891  ldap_bind result is '1'
DEBUG [2019-03-08 11:36:36] 7891  Calling ldap_search([resource], 'dc=mydomain,dc=com', '(&objectClass=user(samaccountname=admin001@mydomain.com))')
WARNING [2019-03-08 11:36:36] 7891  /opt/rh/httpd24/root/var/www/html/piwik/plugins/LoginLdap/Ldap/Client.php(375): Warning - ldap_search(): Search: Bad search filter - Matomo 3.8.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)
DEBUG [2019-03-08 11:36:36] 7891  ldap_search result is 
DEBUG [2019-03-08 11:36:36] 7891  Calling ldap_close([resource])
DEBUG [2019-03-08 11:36:36] 7891  ldap_close returned true
failed!

Synchronized 0 users!

Could not synchronize the following users in LDAP:
admin001@mydomain.com              LDAP search for entries failed. (Unexpected Error, ldap_search returned null)
```
I am misconfiguring something?

**Comment by Jion72** [comment]
I have the same problem

**Comment by jota2016** [comment]
Hi,
The issue persists with new Matomo 3.91.

**Comment by jota2016** [comment]
Hi,
User **HerbstO**, in [this](https://github.com/matomo-org/plugin-LoginLdap/issues/186) post, mentions that by installing the Github version instead of the Marketplace one, it works.
Well, it did the trick for me too.
Matomo v3.91 and plugin 4.07 from Github.
Thanks **HerbstO**.

**Comment by Leboubou111** [comment]
I have the same problem,

I tried to install plugin from Github... same problem.

When I try the "TEST" button to "User group required" or "Filter LDAP search", work fine, display number of users.
But, when I try to "Load user from LDAP" section, I've this error...

`LDAP search for entries failed. (Unexpected Error, ldap_search returned null)`

**Comment by jota2016** [comment]
> I have the same problem,
> 
> I tried to install plugin from Github... same problem.
> 
> When I try the "TEST" button to "User group required" or "Filter LDAP search", work fine, display number of users.
> But, when I try to "Load user from LDAP" section, I've this error...
> 
> `LDAP search for entries failed. (Unexpected Error, ldap_search returned null)`

Hi **Leboubou111**,

Can you post the contents of the config.ini.php file?
Only the part related to the LoginLdap plugin.
Be careful not to post real data about servers, domains, users, passwords, etc.

**Comment by Leboubou111** [comment]
Hi @jota2016 

Of corse 

```
[LoginLdap]
servers[] = "Domain Users"
use_ldap_for_authentication = 0
enable_synchronize_access_from_ldap = 0
new_user_default_sites_view_access = ""
user_email_suffix = ""
required_member_of = "CN=Matomo - Stats,OU=Sites Web,OU=Groupes de S&eacute;curit&eacute;,OU=Organisation,DC=domain,DC=local"
required_member_of_field = "memberOf"
ldap_user_filter = "objectClass=person"
ldap_user_id_field = "sAMAccountName"
ldap_last_name_field = "sn"
ldap_first_name_field = "givenName"
ldap_alias_field = "cn"
ldap_mail_field = "mail"
ldap_password_field = "userPassword"
ldap_view_access_field = "view"
ldap_admin_access_field = "admin"
ldap_superuser_access_field = "superuser"
use_webserver_auth = 0
user_access_attribute_server_specification_delimiter = ";"
user_access_attribute_server_separator = ":"
instance_name = ""
ldap_network_timeout = "15"

[LoginLdap_ProServ Users]
hostname = "users.domain.fr"
port = 389
base_dn = "dc=domain,dc=local"
admin_user = "CN=Browse LDAP,OU=Administration,OU=ProServ,OU=Utilisateurs,OU=Organisation,DC=proserv,DC=local"
admin_pass = "password"
```

I've tried with "userPrincipalName" to "ldap_user_id_field"... Same problem.

**Comment by jota2016** [comment]
Hi,

Try with this changes. You can edit the file directly or through plugin conf within Matomo.

[LoginLdap]
servers[] = "ldap://FQDN of the server"
use_ldap_for_authentication = 1
enable_synchronize_access_from_ldap = 1
required_member_of = "" -->try blank and if it works, then filter.
ldap_user_filter = "(objectClass=person)"
ldap_user_id_field = "SamAccountName"

Set the values exactly as a query returns them from your AD, preserving upper and lower case.

**Comment by Leboubou111** [comment]
Thanks @jota2016.

After many modifications, and restore to my original configuration (less ldap://, with group, etc...) it's work.
I don't kown why.

So, now, how I could configure security with group ? (user A (or group A) access to view site A) ?

**Comment by Leboubou111** [comment]
And I've this message (with the first page) when login to administrator :

`WARNING: /home/gestionpros/sites/stats/plugins/LoginLdap/Ldap/Client.php(146): Warning - ldap_bind(): Unable to bind to server: Can't contact LDAP server - Matomo 3.10.0 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)`

Of course, I've created a issue on Matomo Forum : https://forum.matomo.org/t/ldap-plugin-after-update-matomo-3-9-1-to-3-10/33557

**Comment by Leboubou111** [comment]
Sorry, it’s a bad error --> Resolved.

But, how a I can manage right by AD Group ?
