### ISSUE TITLE
Unable to bind to server: Can't contact LDAP server

### ISSUE THREAD

**Issue by mialynx** [matomo-org/plugin-LoginLdap#179]
php ./console loginldap:synchronize-users -vvv
INFO [2019-03-15 17:17:44] 28545  UserAttributesParser::makeConfigured: Configured with no instance name so matching by URL, but server/site IDs separator set to special ':' character. This character may show up in URLs in LDAP, which will cause problems. We recommend you use a character not often found in URLs, such as '|'.
DEBUG [2019-03-15 17:17:44] 28545  UserSynchronizer::makeConfigured(): Using UserAccessMapper when synchronizing users.
DEBUG [2019-03-15 17:17:44] 28545  UserSynchronizer::makeConfigured: configuring with defaultSitesWithViewAccess = 
DEBUG [2019-03-15 17:17:44] 28545  Model\LdapUsers: start getAllUserLogins() with 
DEBUG [2019-03-15 17:17:44] 28545  Calling ldap_connect('ldaps://ldap.servername.com', 38920)
DEBUG [2019-03-15 17:17:44] 28545  ldap_connect result is [resource]
WARNING [2019-03-15 17:17:44] 28545  /usr/share/matomo/plugins/LoginLdap/Ldap/Client.php(91): Warning - ldap_bind(): Unable to bind to server: Can't contact LDAP server - Matomo 3.8.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)
DEBUG [2019-03-15 17:17:44] 28545  anonymous ldap_bind call finished; connection ok
INFO [2019-03-15 17:17:44] 28545  LdapUsers::makeLdapClient: Using LDAP server ldaps://ldap.servername.com:38920
DEBUG [2019-03-15 17:17:44] 28545  Calling ldap_bind([resource], 'uid=superuser,dc=servername,dc=com', <password[length=24]>)
WARNING [2019-03-15 17:17:44] 28545  /usr/share/matomo/plugins/LoginLdap/Ldap/Client.php(146): Warning - ldap_bind(): Unable to bind to server: Can't contact LDAP server - Matomo 3.8.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already)
DEBUG [2019-03-15 17:17:44] 28545  ldap_bind result is '0'
DEBUG [2019-03-15 17:17:44] 28545  Calling ldap_close([resource])
DEBUG [2019-03-15 17:17:44] 28545  ldap_close returned true

                                 
  [Exception]                    
  Could not bind as LDAP admin.  
                                 

Exception trace:
 () at /usr/share/matomo/plugins/LoginLdap/Model/LdapUsers.php:592
 Piwik\Plugins\LoginLdap\Model\LdapUsers->bindAsAdmin() at /usr/share/matomo/plugins/LoginLdap/Model/LdapUsers.php:307
 Piwik\Plugins\LoginLdap\Model\LdapUsers->Piwik\Plugins\LoginLdap\Model\{closure}() at /usr/share/matomo/plugins/LoginLdap/Model/LdapUsers.php:506
 Piwik\Plugins\LoginLdap\Model\LdapUsers->doWithClient() at /usr/share/matomo/plugins/LoginLdap/Model/LdapUsers.php:325
 Piwik\Plugins\LoginLdap\Model\LdapUsers->getAllUserLogins() at /usr/share/matomo/plugins/LoginLdap/Commands/SynchronizeUsers.php:66
 Piwik\Plugins\LoginLdap\Commands\SynchronizeUsers->execute() at /usr/share/matomo/vendor/symfony/console/Symfony/Component/Console/Command/Command.php:257
 Symfony\Component\Console\Command\Command->run() at /usr/share/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php:874
 Symfony\Component\Console\Application->doRunCommand() at /usr/share/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php:195
 Symfony\Component\Console\Application->doRun() at n/a:n/a
 call_user_func() at /usr/share/matomo/core/Console.php:98
 Piwik\Console->Piwik\{closure}() at /usr/share/matomo/core/Access.php:628
 Piwik\Access::doAsSuperUser() at /usr/share/matomo/core/Console.php:99
 Piwik\Console->doRun() at /usr/share/matomo/vendor/symfony/console/Symfony/Component/Console/Application.php:126
 Symfony\Component\Console\Application->run() at /usr/share/matomo/console:27

loginldap:synchronize-users [--login="..."] [--skip-existing]

connection passes

/usr/bin/ldapsearch  -Z -p 38920 -h ldap.servername.com -b "dc=servername,dc=com" -D uid=superuser,dc=servername,dc=com -w password -z 3 "(objectClass=person)"

**Comment by mattab** [comment]
## Suggestions on fixing this issue

*  try prefixing the LDAP url by `ldaps://` and try again?
* Check the given admin credentials in Matomo's backend 
* also check the Ldap Searchfilter is correct eg. `(objectClass=person)`
* [check for LDAP connection issue.](https://github.com/matomo-org/plugin-LoginLdap/wiki/Troubleshooting#checking-for-an-ldap-server-configuration-issue) by issuing an `ldapsearch` command with the credentials you have configured with your ldap server.
