### ISSUE TITLE
LDAP StartTLS support

### ISSUE THREAD

**Issue by ChristianGfK** [matomo-org/plugin-LoginLdap#184]
Hi,

it's unclear to me if this plugin actually supports using LDAP with StartTLS.
And if yes, which combination of configuration parameters should I use to achieve that?

I have tried various combinations of _Server URL_ with or without _ldap://_ and _ldaps://_ prefix, and _:389_ appended or entered into the _Server Port_ field.

I have tested using the web UI and `console loginldap:synchronize-users --login="user.name" -vvv`, to no avail.
It always gives me conflicting and confusing output (claims "connection ok", but then issues a WARNING that it was unable to bind to the server.)

I'm aware that I'm using an outdated version, but the changelog does not mention StartTLS has been being recently, so I hope that's not relevant.

N.B.: LDAP over SSL (using port 636, which is really an unspecified mode of operation) is currently not an option for me, that port is blocked by firewalls here, sadly.

**Comment by rmfrankch** [comment]
Hi,

I'm pretty much in the same boat, so I dug into the sources.
The class Client in .../plugins/LoginLdap/Ldap defines the methods used to connect. None have the ldap_start_tls() function, so TLS is not implemented. It would, however be really easy by simply adding

if ($needTLS && !ldap_start_tls($this->connectionResource)) {
 ... TLS failed, throw an error
}

before the bind call (line 401). 
Of course, we will als need a flag ($needTLS) in the configuration with which we can turn TLS on or off.
And, you will need the appropriate certificates and ldap.conf.

**Comment by ChristianGfK** [comment]
Seems kind straight-forward at first glance, yeah.
I got our firewall people to unblock port 636 in the meantime, so this has become a side-grade for me now. ;-)

**Comment by dejwsz** [comment]
I tried the plugin with "ldpas" protocol. In the settings test under the filter part apparently works as it shows me how many users it sees in the configured group.  Unfortunately if I try to use it during logging in it does not work.

**Comment by mattab** [comment]
Thanks for your comments! 
We don't have time to look into this now, but we would welcome a pull request implementing support for StartTLS in LDAP plugin. (@rmfrankch provided pointers above what to change in the code) if anyone is able to: https://developer.matomo.org/guides/contributing-to-piwik-core

**Comment by dejwsz** [comment]
OK, so if it still waits why a test is working well ? I mean after filling all the settings I can add "LDAP Search Filter" and run "Test" which is working as it shows me expected value of matched users. Does it mean it was successfully connected over configured ldaps protocol ?

**Comment by ChristianGfK** [comment]
Yes, if the test works, it should work.
Are you using the correct account name?
You can configure this with the `ldap_user_id_field` config option.

Here's my config for comparison:
```
[LoginLdap]
memberOf = ""
filter = "(&amp;(|(memberOf=CN=somegroup,OU=Resource,OU=Groups,OU=X,OU=Germany,DC=Y,DC=com)(memberOf=CN=othergroup,OU=Resource,OU=Groups,OU=X,OU=Germany,DC=Y,DC=com)(memberOf=CN=thirdgroup,OU=Resource,OU=Groups,OU=X,OU=Germany,DC=Y,DC=com))(&amp;(samAccountType=805306368)(!(UserAccountControl:1.2.840.113556.1.4.803:=2))))"
useKerberos = "false"
autoCreateUser = "true"
enable_random_token_auth_generation = 1
new_user_default_sites_view_access = ""
user_email_suffix = ""
ldap_user_id_field = "sAMAccountName"
ldap_last_name_field = "sn"
ldap_first_name_field = "givenName"
ldap_alias_field = "cn"
ldap_mail_field = "mail"
ldap_password_field = "userPassword"
servers[] = "server"
servers[] = "server2"

[LoginLdap_server]
hostname = "ldaps://somehost.y.com"
port = "636"
base_dn = "OU=X,OU=Germany,DC=Y,DC=com"
admin_user = "CN=ldapauth.svc,OU=ServiceAccounts,OU=X,OU=Germany,DC=Y,DC=com"
admin_pass = "hunter2"

[LoginLdap_server2]
hostname = "ldaps://otherhost.y.com"
port = "636"
base_dn = "OU=X,OU=Germany,DC=Y,DC=com"
admin_user = "CN=ldapauth.svc,OU=ServiceAccounts,OU=X,OU=Germany,DC=Y,DC=com"
admin_pass = "hunter2"
```
(This assumes your LDAP is actually Microsoft Active Directory.)

**Comment by dejwsz** [comment]
Thank you, It helped me to configure it better. Though I needed to do one more thing - set CA certificate. I modified '/etc/openldap/ldap.conf' adding this:
    TLS_REQCERT     never
    TLS_CACERT      /usr/local/ssl/certs/myldap.pem
    TLS_CACERTDIR   /usr/local/ssl/certs
And I added the cert in given path.
So now it works for me too.

**Comment by ChristianGfK** [comment]
Sure, yeah. Your system needs to trust the relevant CA for this to work. :-)
Where to add that depends on your particular system.

I imported our certs into OpenLDAP's trust store to make it work:
```
certutil -d /etc/openldap/certs -A -n "Org Root CA" -t CT,, -a -i /etc/pki/ca-trust/source/anchors/org-root-ca.pem
certutil -d /etc/openldap/certs -A -n "Org Sub CA 02" -t CT,, -a -i /etc/pki/ca-trust/source/anchors/org-sub-ca-02.pem
```
