### ISSUE TITLE
Superuser login breaks after upgrade to 3.10.0 as fix unreleased

### ISSUE THREAD

**Issue by sqrt2** [matomo-org/plugin-LoginLdap#189]
Matomo 3.10.0 was released yesterday introducing breaking API changes regarding the granting of superuser rights. A fix was brought in with #185, but a new version of the plugin has not been released yet. As a result, superuser login is broken after a Matomo update.

Current git master works with Matomo 3.10.0.

**Comment by AltamashShaikh** [comment]
@sqrt2 This should be fixed with upgrade to latest version
