### ISSUE TITLE
Entry “Piwik\Auth” cannot be resolved after update to 3.6.0-b4

### ISSUE THREAD

**Issue by froger-me** [matomo-org/plugin-LoginLdap#190]
After updating to 3.6.0-b4, visiting the index shows:

`Entry “Piwik\Auth” cannot be resolved: the class is not instantiableFull definition:Object ( class = #NOT INSTANTIABLE# Piwik\Auth scope = singleton lazy = false)`

The issue is I cannot downgrade back to 3.6.0-b3 (database backup failed).

Could you please indicate either:
- the steps (SQL queries) to downgrade the database manually back to 3.6.0-b3
- a manual quickfix of the 3.6.0-b4 code base

... to (at least) get Matomo back up and running after upgrade to 3.6.0-b4?

**Comment by MichaelHeerklotz** [comment]
The same problem appeared suddenly on my site. It worked before, not it crashes when I run it via command line. Not sure what is causing it.

**Comment by diosmosis** [comment]
FYI, I created a PR to fix this here: https://github.com/matomo-org/matomo/pull/14797
