### ISSUE TITLE
Cannot install Custom Alerts with ldap enabled?

### ISSUE THREAD

**Issue by HatBeardZero** [matomo-org/plugin-LoginLdap#192]
I have an install with loginldap enabled, and when I try to install the plugin (custom alerts), I get the below message.

The plugin Login is not enabled. You can activate the plugin on Settings > Plugins page in Matomo.

**Comment by HatBeardZero** [comment]
This is what i get
![image](https://user-images.githubusercontent.com/9678456/67319946-99fcaf80-f4db-11e9-9276-4fdcf38aadbf.png)

**Comment by tsteur** [comment]
Another issue here: https://forum.matomo.org/t/migration-plugin-requirements/34628/3 seems there was some kind of regression at some point that installing plugin requires the login plugin to be active

**Comment by IWCMoussaS** [comment]
Good morning,
I can see that this issue was reported by "HatBeardZero commented on 22 Oct 2019" is solved.
I'm getting the same issue:
The plugin Login is not enabled. You can activate the plugin on Settings > Plugins page in Matomo.

Cheers

**Comment by sgiehl** [comment]
@IWCMoussaS it's not yet solved

**Comment by sgiehl** [comment]
@diosmosis was that fixed with matomo-org/matomo#16281? Haven't set up an ldap atm so can't easily test that.

**Comment by diosmosis** [comment]
@sgiehl tested installing it via plugin upload and from marketplace, both seem to work. will close this.
